### PR TITLE
github-actions: use github secrets

### PR DESCRIPTION
**Pull request by v1v**
Use GitHub secrets with the needed token.

This will remove the dependency with Vault.

### CODE REVIEW

**Review by trentm — APPROVED** [review]
Approved, but see Q at https://github.com/elastic/apm-agent-nodejs/pull/4129#discussion_r1676161143 about dropping `--otp=...`.

**Review by david-luna — APPROVED** [review]

**Comment by v1v** [comment]
> Approved, but see Q at https://github.com/elastic/apm-agent-nodejs/pull/4129#discussion_r1676161143 about dropping --otp=....

Cross-posting here, there is a meta-issue that explains the rationale for driving this particular change, you are now in the loop. Cheers

**Comment by trentm** [comment]
@v1v Will we need to merge this for a release to work now? I haven't been following the Vault changes.

**Comment by v1v** [comment]
> Will we need to merge this for a release to work now?

This can be merged as soon as we want, the current release workflow should work as is. The proposal here will remove the need for using Vault.

Since I'm now back, we can merge it, when do you plan a new release? I'd like to watch out if things work as expected

**Comment by trentm** [comment]
We have a significant change coming soon (perhaps today) with https://github.com/elastic/elastic-otel-node/pull/279
I might like to go through the release motions with that, before the next change (adding a Docker image publish to the release process).

**Comment by trentm** [comment]
> when do you plan a new release? I'd like to watch out if things work as expected

I'm assuming you saw the release that we did yesterday.

**Pull request merged**
